<?php


/**
 * Implements hook_preprocess_html().
 */
function better_tabs_preprocess_html(&$vars) {
  // Add a class to the body depending on the saved value
  $position = variable_get('better_tabs_dekstop_position', 'left');
  $vars['classes_array'][] = 'bt_' . $position;
}

/**
 * Implements template_preprocess_page().
 */
function better_tabs_preprocess_page($vars) {
  // Check to see if we're not on admin pages
  if (path_is_admin(current_path()) == FALSE) {
    // Add CSS to the header
    drupal_add_css(drupal_get_path('module', 'better_tabs') . '/css/better_tabs.css', array('group' => CSS_DEFAULT));
  }
}

/**
 * Implements hook_menu().
 */
function better_tabs_permission() {
  return array(
    'administer better tabs' => array(
      'title' => t('Administer Better Tabs'),
      'description' => t('Change the appearance of Better Tabs.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function better_tabs_menu() {
  $items['admin/config/administration/bettertabs'] = array(
    'title' => 'Better Tabs',
    'description' => t('Change how Better Tabs is setup on your site.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('better_tabs_settings_form'),
    'access arguments' => array('administer better tabs'),
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function better_tabs_settings_form($node, &$form_state) {
  $form = array();

  $form['desktop_position'] = array(
    '#type' => 'select',
     '#title' => t('Desktop position'),
     '#options' => array(
        'left' => t('Left'),
        'right' => t('Right'),
        'bottom' => t('Bottom'),
     ),
     '#default_value' => variable_get('better_tabs_dekstop_position', 'left'),
     '#description' => t('Choose the position on the tabs on desktop screens.'),
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function better_tabs_settings_form_submit($form, &$form_state) {
  variable_set('better_tabs_dekstop_position', $form_state['values']['desktop_position']);
  drupal_set_message(t('Saved.'), 'status');
}

